// Action type

// login action

export const PROCESS_LOGIN = "PROCESS_LOGIN"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGIN_SUCCESS = "LOGIN_SUCESS"

export const PROCESS_REGISTER = "PROCESS_REGISTER"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const REGISTER_SUCCESS = "REGISTER_SUCESS"

// ACTION TYPE USER DATA
export const PROCESS_ADD_USER_DATA = "PROCESS_ADD_USER_DATA"
export const SUCCESS_ADD_USER_DATA = "SUCCESS_ADD_USER_DAT"
export const FAILED_ADD_USER_DATA = "FAILED_ADD_USER_DATA"