// Action type

// login action

export const PROCESS_LOGIN = "PROCESS_LOGIN"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGIN_SUCCESS = "LOGIN_SUCESS"

export const PROCESS_REGISTER = "PROCESS_REGISTER"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const REGISTER_SUCCESS = "REGISTER_SUCESS"

// ACTION TYPE USER DATA
export const PROCESS_ADD_USER_DATA = "PROCESS_ADD_USER_DATA"
export const SUCCESS_ADD_USER_DATA = "SUCCESS_ADD_USER_DATA"
export const FAILED_ADD_USER_DATA = "FAILED_ADD_USER_DATA"

// ACTION DATA USER
export const PROCESS_DATA_USER = "PROCESS_DATA_USER"
export const SUCCESS_DATA_USER = "SUCCESS_DATA_USER"
export const FAILED_DATA_USER = "FAILED_DATA_USER"

// ACTION GET USER BY ID
export const PROCESS_GET_USER_DETAIL = "PROCESS_GET_USER_DETAIL"
export const PROCESS_GET_USER_SUCCESS = "PROCESS_GET_USER_SUCCESS"
export const PROCESS_GET_USER_FAILED = "PROCESS_GET_USER_FAILED"